
version: 3
jobs:
  build:
    docker:
      - image: circleci/python:3.5-jessie
    steps:
      - checkout
      - run: git config user.name "Shin'ya Ueoka"
      - run: git config user.email "ueokande@i-beam.org"

      - run: pip install --user mkdocs
      - run: ~/.local/bin/mkdocs build

      - checkout:
          path: build
      - run: ( cd build && git checkout gh-pages )

      - run: rm -rf build/$CIRCLE_BRANCH
      - run: mv site build/$CIRCLE_BRANCH
      - run: cd build
      - run: git add .
      - run: git commit -m'Update github pages'

      - add_ssh_keys:
          fingerprints:
            - "e9:c4:2f:89:11:f7:7c:d2:06:be:f3:1b:9f:85:b1:d5"
      - run: git push origin gh-pages
